interface LanguageMap {
    [key: string]: string;
}

export const languageMap: LanguageMap = {
    'en': 'English',
    'de': 'German',
    'ru': 'Russian',
    'hi': 'Hindi',
    'es': 'Spanish',
    'ja': 'Japanese',
    'ko': 'Korean',
    'fr': 'French',
    'hr': 'Croatian',
    'tl': 'Tagalog',
    'pl': 'Polish',
    'lv': 'Latvian',
    'sv': 'Swedish',
    'no': 'Norwegian',
    'it': 'Italian',
    'zh': 'Chinese',
    'uk': 'Ukrainian',
    'id': 'Indonesian',
    'ar': 'Arabic',
    'fi': 'Finnish',
    'pt': 'Portuguese',
    'is': 'Icelandic',
    'nl': 'Dutch',
    'te': 'Telugu',
    'cn': 'Chinese',
    'th': 'Thai',
    'da': 'Danish',
    'hu': 'Hungarian',
    'sr': 'Serbian',
    'ca': 'Catalan',
    'ml': 'Malayalam',
    'yo': 'Yoruba',
    'tr': 'Turkish',
    'el': 'Greek',
    'sh': 'Serbo-Croatian',
    'bn': 'Bengali',
    'cs': 'Czech',
    'fa': 'Persian',
    'ta': 'Tamil',
    'ku': 'Kurdish',
    'kn': 'Kannada',
    'vi': 'Vietnamese',
    'mk': 'Macedonian',
    'sk': 'Slovak',
    'eu': 'Basque',
    'xx': 'Unknown',
    'gl': 'Galician',
    'ga': 'Irish',
    'he': 'Hebrew',
    'mr': 'Marathi',
    'la': 'Latin',
    'ig': 'Igbo',
    'nb': 'Norwegian Bokmål'
};

export const carouselMovies = [
    {
        "_id": "65ce6a264968b47edf6233ab",
        "title": "Oppenheimer",
        "rating": "U/A",
        "time": "3h 1m",
        "genres": [
            "Drama",
            "History"
        ],
        "year": 2023,
        "image": "https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
        "overview": "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II."
    },
    {
        "_id": "65ce6a264968b47edf623435",
        "title": "Avatar",
        "rating": "PG-13",
        "time": "2h 42m",
        "genres": [
            "Action",
            "Adventure",
            "Fantasy",
            "Science Fiction"
        ],
        "year": 2009,
        "image": "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
        "overview": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization."
    },
    {
        "_id": "65ce6a264968b47edf6235c4",
        "title": "Fantastic Beasts and Where to Find Them",
        "rating": "U/A",
        "time": "2h 12m",
        "genres": [
            "Fantasy",
            "Adventure",
            "Family"
        ],
        "year": 2016,
        "image": "https://image.tmdb.org/t/p/w500/h6NYfVUyM6CDURtZSnBpz647Ldd.jpg",
        "overview": "In 1926, Newt Scamander arrives at the Magical Congress of the United States of America with a magically expanded briefcase, which houses a number of dangerous creatures and their habitats. When the creatures escape from the briefcase, it sends the American wizarding authorities after Newt, and threatens to strain even further the state of magical and non-magical relations."
    },
    {
        "_id": "65ce6a264968b47edf6233ff",
        "title": "Interstellar",
        "rating": "PG-13",
        "time": "2h 49m",
        "genres": [
            "Adventure",
            "Drama",
            "Science Fiction"
        ],
        "year": 2014,
        "image": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage."
    },
    {
        "_id": "65ce6a264968b47edf6234b3",
        "title": "Spider-Man: Into the Spider-Verse",
        "rating": "U",
        "time": "1h 57m",
        "genres": [
            "Action",
            "Adventure",
            "Animation",
            "Science Fiction"
        ],
        "year": 2018,
        "image": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        "overview": "Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson \"Kingpin\" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension."
    },
    {
        "_id": "65ce6a264968b47edf6237f8",
        "title": "Mulan",
        "rating": "U",
        "time": "1h 55m",
        "genres": [
            "Adventure",
            "Fantasy",
            "Drama",
            "Action"
        ],
        "year": 2020,
        "image": "https://image.tmdb.org/t/p/w500/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg",
        "overview": "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential."
    },
    {
        "_id": "65ce6a264968b47edf62339c",
        "title": "Wish",
        "rating": "PG",
        "time": "1h 35m",
        "genres": [
            "Animation",
            "Family",
            "Fantasy",
            "Adventure"
        ],
        "year": 2023,
        "image": "https://image.tmdb.org/t/p/w500/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
        "overview": "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen."
    },
    {
        "_id": "65ce6a264968b47edf62341b",
        "title": "The Little Mermaid",
        "rating": "PG",
        "time": "2h 15m",
        "genres": [
            "Adventure",
            "Family",
            "Fantasy",
            "Romance"
        ],
        "year": 2023,
        "image": "https://image.tmdb.org/t/p/w500/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
        "overview": "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy."
    },
    {
        "_id": "65ce6a264968b47edf6233c7",
        "title": "Spider-Man: Across the Spider-Verse",
        "rating": "U/A",
        "time": "2h 20m",
        "genres": [
            "Animation",
            "Action",
            "Adventure",
            "Science Fiction"
        ],
        "year": 2023,
        "image": "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        "overview": "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most."
    }
]

// ['Action' 'Adventure' 'Fantasy' 'Comedy' 'Family' 'Animation'
//  'Science Fiction' 'Drama' 'War' 'Thriller' 'Crime' 'History' 'Romance'
//  'Horror' 'Mystery' 'Music' 'Western' 'TV Movie' 'Documentary']

const adultWords: string[] = [
    "adult",
    "erotic",
    "porn",
    "explicit",
    "nude",
    "sex",
    "xxx",
    "mature",
    "uncensored",
    "fetish",
    "hardcore",
    "sensual",
    "intimate",
    "seductive",
    "naughty",
    "kinky",
    "lust",
    "passionate",
    "orgy",
    "threesome",
    "swinger",
    "bondage",
    "domination",
    "submission",
    "penetration",
    "pleasure",
    "seduction",
    "orgasm",
    "striptease",
    "voyeur",
    "bare",
    "erogenous",
    "stimulation",
    "libido",
    "prostitute",
    "prostitution",
    "eroticism",
    "escort",
    "hooker",
    "whore",
    "lascivious",
    "obscene",
    "promiscuous",
    "raunchy",
    "sordid",
    "titillating",
    "explicit",
    "x-rated",
    "bare",
    "naked",
    "undressed",
    "braless",
    "topless",
    "bottomless",
    "nude",
    "bikini",
    "lingerie",
    "underwear",
    "thong",
    "panties",
    "briefs",
    "boxers",
    "condom",
    "lubricant",
    "sperm",
    "ejaculate",
    "cum",
    "vagina",
    "penis",
    "testicles",
    "breasts",
    "boobs",
    "nipples",
    "anus",
    "buttocks",
    "anal",
    "oral",
    "genital",
    "masturbation",
    "dildo",
    "vibrator",
    "sextoy",
    "fleshlight",
    "pornographic",
    "erotica",
    "porno",
    "kamasutra",
    "adults",
    "swingers",
    "cuckold",
    "hedonism",
    "libertine",
    "kink",
    "fetishism",
    "polyamory",
    "groupsex",
    "sodomy",
    "fornication",
    "hookup",
    "threesome",
    "gangbang",
    "cumshot",
    "facial",
    "creampie",
    "squirting",
    "fisting",
    "rimming",
    "cunnilingus",
    "fellatio",
    "69",
    "analingus",
    "spanking",
    "bdsm",
    "femdom",
    "masturbation",
    "orgasm",
    "erogenous",
    "libido",
    "foreplay",
    "kinky",
    "nymphomaniac",
    "sexpert",
    "playboy",
    "penthouse",
    "hustler",
    "adult",
    "xxx",
    "porn",
    "nude",
    "erotic",
    "kamasutra",
    "sex",
    "naked",
    "sensual",
    "intimate",
    "lust",
    "seductive",
    "explicit",
    "passionate",
    "orgy",
    "threesome",
    "swinger",
    "bondage",
    "domination",
    "submission",
    "penetration",
    "pleasure",
    "seduction",
    "orgasm",
    "striptease",
    "voyeur",
    "bare",
    "erogenous",
    "stimulation",
    "libido",
    "prostitute",
    "escort",
    "hooker",
    "whore",
    "lascivious",
    "obscene",
    "promiscuous",
    "raunchy",
    "sordid",
    "titillating",
    "x-rated"
];

// Example usage:
// You can use this array to filter content or check if a word exists in a string.
// For example:
// const userInput: string = "I enjoy watching sensual movies.";
// const containsAdultContent: boolean = adultWords.some(word => userInput.toLowerCase().includes(word));
// console.log(containsAdultContent); // Output: true
